include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
  plugins:
    - dart_code_metrics

linter:
  rules:
    public_member_api_docs: false

dart_code_metrics:
  extends:
    - package:dart_code_metrics/presets/flutter_all.yaml
  rules:
    prefer-single-widget-per-file: false